# Generated by Django 2.1.1 on 2018-09-09 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TkApp', '0001_initial'),
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
            ],
            options={
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('subjectID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TkApp.title', verbose_name='收藏ID')),
            ],
            options={
                'verbose_name_plural': '用户收藏ID',
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('subjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TkApp.title', verbose_name='错题ID')),
            ],
            options={
                'verbose_name_plural': '用户错题ID',
            },
        ),
        migrations.CreateModel(
            name='Finished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('subjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TkApp.title', verbose_name='已做题目ID')),
            ],
            options={
                'verbose_name_plural': '用户已做题目ID',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='User_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=30, verbose_name='性别')),
                ('experience', models.IntegerField(verbose_name='经验')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
                ('ClassroomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Classroom', verbose_name='所属班级')),
                ('bookID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BookApp.book', verbose_name='所学内容')),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserApp.User', verbose_name='所属用户')),
            ],
            options={
                'verbose_name_plural': '个人信息',
            },
        ),
        migrations.AddField(
            model_name='finished',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='error',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='collection',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.User', verbose_name='用户'),
        ),
    ]
