# Generated by Django 2.0.7 on 2018-07-30 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20180725_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='subjectID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TkApp.title', verbose_name='收藏ID'),
        ),
        migrations.AlterField(
            model_name='information',
            name='experience',
            field=models.IntegerField(max_length=30, verbose_name='经验'),
        ),
    ]
