# Generated by Django 2.0.7 on 2018-07-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
        ('UserApp', '0004_auto_20180730_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information',
            new_name='User_Information',
        ),
    ]
