# Generated by Django 2.0.7 on 2018-08-10 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_auto_20180730_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finished',
            options={'verbose_name_plural': '用户已做题目ID'},
        ),
    ]
