# Generated by Django 2.1.1 on 2018-09-09 02:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='试卷')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
            ],
            options={
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
                ('examID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TkApp.Exam', verbose_name='所属试卷')),
            ],
            options={
                'verbose_name_plural': '试卷题目',
            },
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=60, verbose_name='答案')),
                ('types', models.CharField(choices=[('单选', '单选'), ('多选', '多选'), ('判断', '判断')], max_length=60, verbose_name='题型')),
                ('difficulty', models.IntegerField(blank=True, null=True, verbose_name='难度等级')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='备注')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
                ('minutiaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookApp.Measure', verbose_name='小节ID')),
            ],
            options={
                'verbose_name_plural': '答案',
            },
        ),
        migrations.CreateModel(
            name='more',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerA', models.CharField(max_length=60, verbose_name='选项A')),
                ('AnswerB', models.CharField(max_length=60, verbose_name='选项B')),
                ('AnswerC', models.CharField(max_length=60, verbose_name='选项C')),
                ('AnswerD', models.CharField(max_length=60, verbose_name='选项D')),
                ('AnswerE', models.CharField(max_length=60, verbose_name='选项E')),
                ('AnswerF', models.CharField(max_length=60, verbose_name='选项F')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
            ],
            options={
                'verbose_name_plural': '多选内容',
            },
        ),
        migrations.CreateModel(
            name='radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerA', models.CharField(max_length=60, verbose_name='选项A')),
                ('AnswerB', models.CharField(max_length=60, verbose_name='选项B')),
                ('AnswerC', models.CharField(max_length=60, verbose_name='选项C')),
                ('AnswerD', models.CharField(max_length=60, verbose_name='选项D')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
            ],
            options={
                'verbose_name_plural': '单选内容',
            },
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='题目')),
                ('isDelete', models.BooleanField(default=True, verbose_name='是否可用')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改日期')),
            ],
            options={
                'verbose_name_plural': '题目',
            },
        ),
        migrations.AddField(
            model_name='radio',
            name='subjectID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TkApp.title', verbose_name='题目ID'),
        ),
        migrations.AddField(
            model_name='more',
            name='subjectID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TkApp.title', verbose_name='题目ID'),
        ),
        migrations.AddField(
            model_name='information',
            name='subjectID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TkApp.title', verbose_name='题目ID'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='subjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TkApp.title', verbose_name='题目ID'),
        ),
    ]
