# Generated by Django 2.0.7 on 2018-07-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TkApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='note',
            field=models.CharField(blank=True, max_length=300, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='information',
            name='types',
            field=models.CharField(choices=[('单选', '单选'), ('多选', '多选'), ('判断', '判断')], max_length=60, verbose_name='题型'),
        ),
    ]
