# Generated by Django 2.0.7 on 2018-07-30 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TkApp', '0002_auto_20180725_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='minutiaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookApp.Measure', verbose_name='小节ID'),
        ),
        migrations.AlterField(
            model_name='information',
            name='subjectID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TkApp.title', verbose_name='题目ID'),
        ),
        migrations.AlterField(
            model_name='more',
            name='subjectID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TkApp.title', verbose_name='题目ID'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='subjectID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TkApp.title', verbose_name='题目ID'),
        ),
    ]
