# Generated by Django 2.0.7 on 2018-08-07 06:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TkApp', '0003_auto_20180730_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='subject',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='题目'),
        ),
    ]
